### ISSUE TITLE
v2.5.1 URI Metric and Infrastructure SQL errror

### ISSUE THREAD

**Issue by CN-RexYeung** [pinpoint-apm/pinpoint-docker#174]
I have installed version v2.5.1 using Docker Compose, and the servermap and inspector functions are normal, but the URI Metric and Infrastructure functions indicate SQL errors. After my simple investigation, it was found that there are missing data tables in the database. Do I need to perform additional SQL initialization?

**Comment by CN-RexYeung** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-docker/assets/61341983/697098fa-045a-4a8a-b68b-b997ae3de89a)

**Comment by CN-RexYeung** [comment]
![image](https://github.com/pinpoint-apm/pinpoint-docker/assets/61341983/818edbfb-b46a-400e-a708-bf011f1dd209)

**Comment by ga-ram** [comment]
```
docker-compose -f docker-compose.yml -f docker-compose-metric.yml restart pinot-init
```
above command will restart pinot initializing process and will create necessary tables.

Current docker compose script just waits a few seconds after starting up the pinot containers and then run the init commands, and it seems like the waiting time is not enough (and it varies according to each environment also).
It would be great if you can contribute to modify that script so that it can wait until all the containers are ready and then run the init commands.
